### ISSUE TITLE
"me" in UserInfo["data"]: TypeError

### ISSUE THREAD

**Issue by thoward02** [thoward02/insightsGG#1]
```[LOG] Setting up insights...
[LOG] Done.
[LOG] Logging into Insights...
Traceback (most recent call last):
  File "C:\Users\thoward20\Documents\GitHub\HCC_DataManager\Main.py", line 526, in <module>
    Primary = PrimaryApp(sys.argv[1], sys.argv[2])
  File "C:\Users\thoward20\Documents\GitHub\HCC_DataManager\Main.py", line 27, in __init__
    self.App.Login(Username, Password)
  File "C:\Users\thoward20\AppData\Local\Programs\Python\Python38-32\lib\site-packages\insightsGG\App.py", line 54, in Login
    self.User  = self.BuildUser()
  File "C:\Users\thoward20\AppData\Local\Programs\Python\Python38-32\lib\site-packages\insightsGG\App.py", line 80, in BuildUser
    if "me" in UserInfo["data"]:
TypeError: argument of type 'NoneType' is not iterable```
```
Sometimes is tossed during login for no reason???

**Comment by thoward02** [comment]
The last time I saw this issue was in late Dec. Since we have multiple active users, and no further reports of this, I'm closing this issue.
